apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: oracle-connector
  labels:
    strimzi.io/cluster: oracle-connect
  namespace: openshift-operators
spec:
  config:
     table.include.list: hr.c1
     database.hostname : 10.107.88.174
     database.port : 1521  
     database.user : dbz
     database.password : dbz
     database.dbname : laiora19c
     database.server.name : laiora19c  
     database.url : jdbc:oracle:thin:@//10.107.88.174:1521/laiora19c
     database.history.kafka.bootstrap.servers : my-cluster-kafka-bootstrap:9092 
     database.history.kafka.topic: oracle-schema-changes.inventory
     transforms: filter
     transforms.filter.type: io.debezium.transforms.Filter
     transforms.filter.language: jsr223.groovy
     transforms.filter.topic.regex: laiora19c.HR.T2
     transforms.filter.condition: value.op == 'u' || value.op == 'c' || value.op == 'd'
  class: io.debezium.connector.oracle.OracleConnector
  tasksMax: 1
