apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: mongodb-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: mongodb-connect-cluster
    offset.storage.topic: mongodb-connect-cluster-offsets
    config.storage.topic: mongodb-connect-cluster-configs
    status.storage.topic: mongodb-connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  image: docker.io/georgechiu/plugins7
